/*!
 * ISC License
 *
 * Copyright (c) 2026, Imqueue Sandbox
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
import type { PayloadError } from 'relay-runtime';
import type { loginMutation$data } from './relay/mutations/__generated__/loginMutation.graphql';

/**
 * Types which GraphQL does not describe.
 *
 * The domain model of this app is *not* declared here: it is generated by
 * relay-compiler out of the queries, fragments and mutations themselves and
 * lives in the `__generated__` directories next to them. Components take their
 * props straight from those artifacts (`UserCars$data`, `AppRootQuery$data`, …),
 * so the shape a component accepts is provably the shape its GraphQL document
 * selects — add a field to a fragment and the prop type follows automatically.
 *
 * What remains here is everything outside that pipeline: the error shape the
 * gateway adds on top of Relay's, the data-operation callbacks, and the session
 * record this app persists locally.
 *
 * The REST sibling front-end (`web-app-rest`) has no compiler to generate types
 * from, so it declares its whole domain model by hand instead. The two apps
 * deliberately differ here — each is typed the way its own transport wants to be.
 */

/**
 * A back-end error as surfaced to the view layer.
 *
 * Relay models a GraphQL error as `PayloadError`, which omits the spec's
 * `extensions` member. The gateway uses `extensions` to carry a machine-readable
 * `code` (for example `USER_EMAIL_ERROR`) which the login form maps onto the
 * offending input, so it is declared here on top of Relay's own type.
 */
export interface AppError extends PayloadError {
    extensions?: {
        code?: string;
        [key: string]: unknown;
    };
}

/** Called with the payload of a successful data operation. */
export type SuccessHandler<T = unknown> = (data: T) => void;

/** Called with the list of errors of a failed data operation. */
export type FailureHandler = (errors: AppError[]) => void;

/**
 * The authenticated identity, as persisted in `AppStore` under `AUTH_KEY`.
 *
 * This is the `login` mutation payload verbatim — the stored session record and
 * the mutation result are one and the same value.
 */
export type AuthInfo = NonNullable<loginMutation$data['login']>;
